### PR TITLE
Get rid of old webinterface support.

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by petrkr** [comment]
Nooooooo :( that blue one? Always switching to "legacy" webif since that new is unusable, ugly and big

**Comment by persianpros** [comment]
No it's not about that, it's about Dreambox's webinterface ;)

**Comment by petrkr** [comment]
Aha :) Uffff good. Don't do such things at saturday to me :)

**Comment by persianpros** [comment]
LOL

**Pull request merged**
